[GLOBAL]
pants_version = "2.11.0"
backend_packages = [
    "pants.backend.python"
]

[python]
interpreter_constraints = [">=3.9,<3.11"]
enable_resolves = true
resolves_generate_lockfiles = false

[python.resolves]
python-default = "3rdparty/python-default/python-default.lock"

[anonymous-telemetry]
enabled = true
