python_sources(
    resolve="helloworld"
)

python_requirements(
    name="requirements.txt",
    resolve="helloworld"
)

pex_binary(
    name="main",
    entry_point="main.py",
    resolve="helloworld"
)
