[tool.poetry]
name = "python-default"
version = "0.1.0"
description = "Default universe of dependencies for Python projects."
authors = ["Soheil Salmani <salmani.soheil@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.4"
click = "^8.1.3"
pandas = "^1.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
